[package]
name = "portscan"
version = "0.1.1"
authors = ["Srikanth Suresh <4140019+srikwit@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
